# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  instance:
    hostname: localhost
    port: 8082
server:
  port: 8083
spring:
  application:
    name: user-service
  redis:
    database: 0
    host: 120.79.14.47
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true