server:
  port: 8081
spring:
  redis:
    database: 0
    host: 120.79.14.47
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
  application:
    name: market-base
  #数据库配置
  datasource:
    name: aliyunDatasource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.14.47:3306/shop_kermi_test
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  rabbitmq:
    host: 120.79.14.47
# mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/**/*xml
  type-aliases-package: com.kermi.common.mapper
logging:
  level:
    com.kermi.common.mapper: debug
# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  instance:
    hostname: localhost
    port: 8082